# Generated by Django 5.2.4 on 2026-05-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='ministries.ministry')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('signature_count', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting_signatures', 'Collecting Signatures'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=25)),
                ('target_ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='ministries.ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='public_participation.consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='public_part_status_ca46f6_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['ministry', 'is_active'], name='public_part_ministr_369d96_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['reference'], name='public_part_referen_60ca73_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['status'], name='public_part_status_1c3b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['target_ministry'], name='public_part_target__ac9e29_idx'),
        ),
        migrations.AddIndex(
            model_name='publiccomment',
            index=models.Index(fields=['consultation', 'is_approved'], name='public_part_consult_92b802_idx'),
        ),
    ]
