"""
Load the Constitution of Kenya, 2010 into the database.

Usage: python manage.py load_constitution
"""
from django.core.management.base import BaseCommand
from apps.constitution.models import Chapter, Article, Schedule


CONSTITUTION = [
    {
        'number': 1, 'title': 'Sovereignty of the People and Supremacy of this Constitution',
        'subtitle': 'Articles 1–3',
        'overview': 'Declares that all sovereign power belongs to the people of Kenya, establishes the supremacy of the Constitution over all other laws, and obligates every person to respect, uphold and defend it.',
        'articles': [
            ('1', 'Sovereignty of the people', 'All sovereign power belongs to the people of Kenya and shall be exercised only in accordance with this Constitution. The people may exercise their sovereign power either directly or through their democratically elected representatives. Sovereign power is delegated to Parliament and the legislative assemblies in the county governments, the national executive and the executive structures in the county governments, and the Judiciary and independent tribunals. The sovereign power of the people shall be exercised at the national level and the county level.'),
            ('2', 'Supremacy of this Constitution', 'This Constitution is the supreme law of the Republic and binds all persons and all State organs at both levels of government. No person may claim or exercise State authority except as authorised under this Constitution. The validity or legality of this Constitution is not subject to challenge by or before any court or other State organ. Any law, including customary law, that is inconsistent with this Constitution is void to the extent of the inconsistency, and any act or omission in contravention of this Constitution is invalid. The general rules of international law shall form part of the law of Kenya. Any treaty or convention ratified by Kenya shall form part of the law of Kenya under this Constitution.'),
            ('3', 'Defence of this Constitution', 'Every person has an obligation to respect, uphold and defend this Constitution. Any attempt to establish a government otherwise than in compliance with this Constitution is unlawful.'),
        ],
    },
    {
        'number': 2, 'title': 'The Republic',
        'subtitle': 'Articles 4–11',
        'overview': 'Defines Kenya as a sovereign republic, outlines its territory, devolution structure, official languages, national symbols, national days, national values and culture.',
        'articles': [
            ('4', 'Declaration of the Republic', 'Kenya is a sovereign Republic. The Republic of Kenya shall be a multi-party democratic State founded on the national values and principles of governance referred to in Article 10.'),
            ('5', 'Territory of Kenya', 'Kenya consists of the territory and territorial waters comprising Kenya on the effective date, and any additional territory and territorial waters as defined by an Act of Parliament. The territory of Kenya is divided into the counties specified in the First Schedule.'),
            ('6', 'Devolution and access to services', 'The territory of Kenya is divided into forty-seven counties. The governments at the national and county levels are distinct and inter-dependent and shall conduct their mutual relations on the basis of consultation and cooperation. For every county government, there shall be a county assembly and a county executive.'),
            ('7', 'National, official and other languages', 'The national language of the Republic is Kiswahili. The official languages are Kiswahili and English. The State shall promote and protect the diversity of language of the people of Kenya and promote the development and use of indigenous languages, Kenyan Sign language, Braille and other communication formats.'),
            ('8', 'State and religion', 'There shall be no State religion.'),
            ('9', 'National symbols and national days', 'The national symbols are the national flag, the national anthem, the coat of arms and the public seal. The national days are Madaraka Day (1st June), Mashujaa Day (20th October), and Jamhuri Day (12th December).'),
            ('10', 'National values and principles of governance', 'The national values and principles of governance include: patriotism, national unity, sharing and devolution of power, the rule of law, democracy and participation of the people, human dignity, equity, social justice, inclusiveness, equality, human rights, non-discrimination and protection of the marginalised, good governance, integrity, transparency and accountability, and sustainable development.'),
            ('11', 'Culture', 'This Constitution recognises culture as the foundation of the nation and as the cumulative civilization of the Kenyan people and nation. The State shall promote all forms of national and cultural expression through literature, the arts, traditional celebrations, science, communication, information, mass media, publications, libraries and other cultural heritage.'),
        ],
    },
    {
        'number': 3, 'title': 'National Executive',
        'subtitle': 'Articles 12–15',
        'overview': 'Establishes citizenship by birth and registration, outlines grounds for revocation, sets residency rules, and mandates legislation on the Kenya Citizenship Act.',
        'articles': [
            ('12', 'Entitlements of citizens', 'Every citizen is entitled to the rights, privileges and benefits of citizenship, and to a Kenyan passport and any document of registration or identification issued by the State. A citizen may be deprived of citizenship only in accordance with legislation.'),
            ('13', 'Retention and acquisition of citizenship', 'Every person who was a citizen immediately before the effective date retains citizenship. A person who has been married to a citizen for at least seven years is entitled to apply for citizenship. A child found in Kenya who appears to be under eight years of age and whose nationality is unknown is presumed to be a citizen.'),
            ('14', 'Citizenship by birth', 'A person is a citizen by birth if at the date of their birth, whether born in Kenya or not, either their mother or father is a citizen. A child found in Kenya who is, or appears to be, less than eight years of age, and whose nationality and parents are not known, is presumed to be a citizen.'),
            ('15', 'Citizenship by registration', 'A person who has been lawfully resident in Kenya for a continuous period of at least seven years and who satisfies conditions prescribed by an Act of Parliament may apply for citizenship by registration.'),
        ],
    },
    {
        'number': 4, 'title': 'The Bill of Rights',
        'subtitle': 'Articles 19–59',
        'overview': 'The most comprehensive section of the Constitution. Enshrines fundamental rights and freedoms including the right to life, equality, human dignity, freedom and security of the person, privacy, freedom of expression, association, movement, and economic and social rights.',
        'articles': [
            ('19', 'Rights and fundamental freedoms', 'The Bill of Rights is an integral part of Kenya\'s democratic state and is the framework for social, economic and cultural policies. The purpose of recognising and protecting human rights and fundamental freedoms is to preserve the dignity of individuals and communities and to promote social justice. The rights and fundamental freedoms in the Bill of Rights belong to each individual and are not granted by the State.'),
            ('20', 'Application of Bill of Rights', 'The Bill of Rights applies to all law and binds all State organs and all persons. Every person shall enjoy the rights and fundamental freedoms in the Bill of Rights to the greatest extent consistent with the nature of the right or fundamental freedom. In interpreting the Bill of Rights, a court, tribunal or other authority shall promote the values of an open and democratic society, the spirit and objects of the Bill of Rights, and may consider foreign law.'),
            ('21', 'Implementation of rights and fundamental freedoms', 'It is a fundamental duty of the State and every State organ to observe, respect, protect, promote and fulfil the rights and fundamental freedoms in the Bill of Rights. The State shall take legislative, policy and other measures for the progressive realisation of the rights guaranteed under Article 43.'),
            ('22', 'Enforcement of Bill of Rights', 'Every person has the right to institute court proceedings claiming that a right or fundamental freedom in the Bill of Rights has been denied, violated, infringed or threatened. In addition to a person acting in their own interest, court proceedings may be instituted by a person acting on behalf of another person, a person acting as a member of a group or class, a person acting in the public interest, or an association acting in the interest of its members.'),
            ('23', 'Authority of courts to uphold and enforce the Bill of Rights', 'The High Court has jurisdiction to hear and determine applications for redress of a denial, violation or infringement of, or threat to, a right or fundamental freedom. In any proceedings, a court may grant appropriate relief, including a declaration of rights, an injunction, a conservatory order, a declaration of invalidity of any law, an order for compensation, or an order of judicial review.'),
            ('24', 'Limitation of rights and fundamental freedoms', 'A right or fundamental freedom in the Bill of Rights shall not be limited except by law, and then only to the extent that the limitation is reasonable and justifiable in an open and democratic society. In determining reasonableness, the court shall consider the nature of the right, the importance of the limitation, the nature and extent of the limitation, and whether there are less restrictive means.'),
            ('25', 'Fundamental Rights and Freedoms that may not be limited', 'Despite any other provision in this Constitution, the following rights and fundamental freedoms shall not be limited: freedom from torture and cruel, inhuman or degrading treatment or punishment; freedom from slavery or servitude; the right to a fair trial; and the right to an order of habeas corpus.'),
            ('26', 'Right to life', 'Every person has the right to life. A person shall not be deprived of life intentionally, except to the extent authorised by this Constitution or other written law. Abortion is not permitted unless, in the opinion of a trained health professional, there is need for emergency treatment, or the life or health of the mother is in danger.'),
            ('27', 'Equality and freedom from discrimination', 'Every person is equal before the law and has the right to equal protection and equal benefit of the law. Women and men have the right to equal treatment, including the right to equal opportunities in political, economic, cultural and social spheres. The State shall not discriminate directly or indirectly against any person on any ground.'),
            ('28', 'Human dignity', 'Every person has inherent dignity and the right to have that dignity respected and protected.'),
            ('29', 'Freedom and security of the person', 'Every person has the right to freedom and security of the person, which includes the right not to be deprived of freedom arbitrarily, not to be detained without trial, to be free from all forms of violence, and not to be treated or punished in a cruel, inhuman or degrading manner.'),
            ('30', 'Slavery, servitude and forced labour', 'A person shall not be held in slavery or servitude. A person shall not be required to perform forced labour.'),
            ('31', 'Privacy', 'Every person has the right to privacy, which includes the right not to have their person, home or property searched, their possessions seized, information relating to their family or private affairs unnecessarily required or revealed, or the privacy of their communications infringed.'),
            ('32', 'Freedom of conscience, religion, belief and opinion', 'Every person has the right to freedom of conscience, religion, thought, belief and opinion. Every person has the right, either individually or in community with others, to manifest any religion or belief through worship, practice, teaching or observance. A person shall not be denied access to any institution, employment or facility on the grounds of religion.'),
            ('33', 'Freedom of expression', 'Every person has the right to freedom of expression, which includes freedom to seek, receive or impart information or ideas, freedom of artistic creativity, and academic freedom and freedom of scientific research. This right does not extend to propaganda for war, incitement to violence, hate speech, or advocacy of hatred.'),
            ('34', 'Freedom of the media', 'Freedom and independence of electronic, print and all other types of media is guaranteed. The State shall not exercise control over or interfere with any person engaged in broadcasting, the production or circulation of publications, or the dissemination of information. Broadcasting and other electronic media shall be free to establish standards of good practice.'),
            ('35', 'Access to information', 'Every citizen has the right of access to information held by the State, and information held by another person required for the exercise or protection of any right or fundamental freedom. Every person has the right to the correction or deletion of untrue or misleading information affecting them.'),
            ('36', 'Freedom of association', 'Every person has the right to freedom of association, which includes the right to form, join or participate in the activities of an association of any kind. A person shall not be compelled to join an association of any kind.'),
            ('37', 'Assembly, demonstration, picketing and petition', 'Every person has the right, peaceably and unarmed, to assemble, to demonstrate, to picket, and to present petitions to public authorities.'),
            ('38', 'Political rights', 'Every citizen is free to make political choices, which includes the right to form or participate in a political party, to participate in the activities of a political party, or to campaign for a political party or cause. Every citizen has the right to free, fair and regular elections.'),
            ('39', 'Freedom of movement and residence', 'Every person has the right to freedom of movement. Every person has the right to leave Kenya. Every citizen has the right to enter, remain in and reside anywhere in Kenya.'),
            ('40', 'Protection of right to property', 'Subject to Article 65, every person has the right, either individually or in association with others, to acquire and own property of any description in any part of Kenya. Parliament shall not enact a law that permits the State or any person to arbitrarily deprive a person of property.'),
            ('41', 'Labour relations', 'Every person has the right to fair labour practices. Every worker has the right to fair remuneration, reasonable working conditions, to form, join or participate in a trade union, and to strike. Every employer has the right to form and join an employers\' organisation and to participate in its activities.'),
            ('42', 'Environment', 'Every person has the right to a clean and healthy environment, which includes the right to have the environment protected for the benefit of present and future generations through legislative and other measures. Every person has the obligation to cooperate with State organs to protect and conserve the environment.'),
            ('43', 'Economic and social rights', 'Every person has the right to the highest attainable standard of health, accessible and adequate housing, to be free from hunger and to adequate food of acceptable quality, to clean and safe water in adequate quantities, to social security, and to education. A person shall not be denied emergency medical treatment.'),
            ('44', 'Language and culture', 'Every person has the right to use the language, and to participate in the cultural life, of the person\'s choice. A person belonging to a cultural or linguistic community has the right to enjoy their culture, practice their religion, and use their language.'),
            ('45', 'Family', 'The family is the natural and fundamental unit of society and the necessary basis of social order, and shall enjoy the recognition and protection of the State. Every adult has the right to marry a person of the opposite sex, based on the free consent of the parties.'),
            ('46', 'Consumer rights', 'Consumers have the right to goods and services of reasonable quality, to the information necessary for them to gain full benefit from goods and services, to the protection of their health and safety, and to compensation for loss or injury arising from defects in goods or services.'),
            ('47', 'Fair administrative action', 'Every person has the right to administrative action that is expeditious, efficient, lawful, reasonable and procedurally fair. If a right or fundamental freedom has been or is likely to be adversely affected, the person has the right to be given written reasons for the action.'),
            ('48', 'Access to justice', 'The State shall ensure access to justice for all persons and, if any fee is required, it shall be reasonable and shall not impede access to justice.'),
            ('49', 'Rights of arrested persons', 'An arrested person has the right to be informed promptly of the reason for the arrest, to remain silent, to communicate with an advocate, to be brought before a court within twenty-four hours, and to be released on bond or bail pending trial.'),
            ('50', 'Fair hearing', 'Every person has the right to have any dispute that can be resolved by the application of law decided in a fair and public hearing before a court or an independent and impartial tribunal. Every accused person has the right to a fair trial, which includes the right to be presumed innocent, to be informed of the charge, to have adequate time and facilities to prepare a defence, and to have the trial begin and conclude without unreasonable delay.'),
            ('51', 'Rights of persons detained, held in custody or imprisoned', 'A person who is detained, held in custody or imprisoned retains all the rights and fundamental freedoms in the Bill of Rights, except to the extent that any particular right is incompatible with the fact that the person is detained.'),
            ('52', 'Interpretation of this Part', 'This Part shall be interpreted in a manner that promotes the values and principles underlying an open and democratic society, human dignity, equality, and the freedom and security of the person.'),
            ('53', 'Children', 'Every child has the right to a name and nationality from birth, to free and compulsory basic education, to basic nutrition, shelter and health care, to be protected from abuse, neglect, harmful cultural practices and all forms of violence, and not to be detained except as a measure of last resort.'),
            ('54', 'Persons with disabilities', 'A person with any disability is entitled to be treated with dignity and respect, to access educational institutions and facilities, to reasonable access to all places and public transport, to use Sign language, Braille or other means of communication, and to access materials and devices to overcome constraints.'),
            ('55', 'Youth', 'The State shall take measures to ensure that the youth access relevant education and training, have opportunities to participate in political, social and economic spheres, and are protected from harmful cultural practices and exploitation.'),
            ('56', 'Minorities and marginalised groups', 'The State shall put in place affirmative action programmes designed to ensure that minorities and marginalised groups participate and are represented in governance and other spheres of life, are provided special opportunities in education and economic fields, and have reasonable access to water, health services and infrastructure.'),
            ('57', 'Older members of society', 'The State shall take measures to ensure the rights of older persons to fully participate in the affairs of society, to pursue their personal development, to live in dignity and respect, free from abuse, and to receive reasonable care and assistance from their family and the State.'),
            ('58', 'State of emergency', 'A state of emergency may be declared only under Article 132 and only when the State is threatened by war, invasion, general insurrection, disorder, natural disaster or other public emergency. A declaration of a state of emergency shall be submitted to the National Assembly within twenty-four hours.'),
            ('59', 'Kenya National Human Rights and Equality Commission', 'There is established the Kenya National Human Rights and Equality Commission whose functions include promoting respect for human rights, receiving complaints about alleged abuses, monitoring and reporting on the observance of human rights, and taking steps to secure appropriate redress.'),
        ],
    },
    {
        'number': 5, 'title': 'Land and Environment',
        'subtitle': 'Articles 60–72',
        'overview': 'Establishes principles of land policy, classification of land (public, community, private), the National Land Commission, environmental obligations, and regulation of land use and property.',
        'articles': [
            ('60', 'Principles of land policy', 'Land in Kenya shall be held, used and managed in a manner that is equitable, efficient, productive and sustainable, and in accordance with the principles of equitable access, security of land rights, sustainable management, transparent administration, and conservation of ecologically sensitive areas.'),
            ('61', 'Classification of land', 'All land in Kenya belongs to the people of Kenya collectively as a nation, as communities and as individuals. Land in Kenya is classified as public land, community land or private land.'),
            ('62', 'Public land', 'Public land includes land occupied, used or set aside for public purposes, land transferred to the State by way of reversion or surrender, land in respect of which no individual or community ownership can be established, and land which no heir can be identified. Public land shall vest in and be held by the national government or county governments.'),
            ('63', 'Community land', 'Community land shall vest in and be held by communities identified on the basis of ethnicity, culture or similar community of interest. Community land includes land registered in the name of group representatives, land transferred to a specific community by law, and any land declared to be community land by an Act of Parliament.'),
            ('64', 'Private land', 'Private land consists of registered land held by any person under a freehold or leasehold tenure.'),
            ('65', 'Landholding by non-citizens', 'A person who is not a citizen may hold land on the basis of leasehold tenure only, and any such lease shall not exceed ninety-nine years.'),
            ('66', 'Regulation of land use and property', 'The State may regulate the use of any land, or any interest in or right over any land, in the interest of defence, public safety, public order, public morality, public health, or land use planning.'),
            ('67', 'National Land Commission', 'There is established the National Land Commission. The functions of the Commission include managing public land on behalf of the national and county governments, recommending a national land policy, advising the national government on a comprehensive programme for the registration of title in land, and conducting research related to land.'),
            ('68', 'Legislation on land', 'Parliament shall enact legislation to revise, consolidate and rationalise existing land laws, prescribe minimum and maximum land holding acreages, regulate land use, and regulate the recognition and registration of community land rights.'),
            ('69', 'Obligations in respect of the environment', 'The State shall ensure sustainable exploitation, utilisation, management and conservation of the environment, work to achieve and maintain a tree cover of at least ten per cent, protect and enhance intellectual property in indigenous knowledge, and encourage public participation in environmental management.'),
            ('70', 'Enforcement of environmental rights', 'If a person alleges that a right to a clean and healthy environment has been or is likely to be contravened, the person may apply to the Environment and Land Court for redress.'),
            ('71', 'Agreements relating to natural resources', 'A transaction is subject to ratification by Parliament if it involves the grant of a right or concession for the exploitation of any natural resource of Kenya.'),
            ('72', 'Legislation relating to the environment', 'Parliament shall enact legislation to give full effect to the provisions of this Part.'),
        ],
    },
    {
        'number': 6, 'title': 'Representation of the People',
        'subtitle': 'Articles 81–92',
        'overview': 'Covers the electoral system and process, the Independent Electoral and Boundaries Commission (IEBC), political parties, and principles of representation.',
        'articles': [
            ('81', 'General principles for the electoral system', 'The electoral system shall comply with the principles of freedom of citizens to exercise their political rights, gender equity, fair representation of persons with disabilities, universal suffrage, free and fair elections by secret ballot, and freedom from violence or corruption.'),
            ('82', 'Legislation on elections', 'Parliament shall enact legislation to provide for the delimitation of electoral units, the nomination of candidates, the continuous registration of voters, the conduct of elections and referenda, and the progressive registration of citizens residing outside Kenya.'),
            ('83', 'Registration as a voter', 'A person qualifies for registration as a voter if the person is an adult citizen, is not declared to be of unsound mind, and has not been convicted of an election offence during the preceding five years.'),
            ('84', 'Candidates for election and compliance with code of conduct', 'Every candidate for an election shall comply with the code of conduct for political parties and candidates.'),
            ('85', 'Eligibility to stand as an independent candidate', 'Any person is eligible to stand as an independent candidate for election if the person is not a member of a registered political party, has not been a member of any political party for at least three months immediately before the date of the election, and satisfies the nomination requirements.'),
            ('86', 'Voting', 'At every election, the Independent Electoral and Boundaries Commission shall ensure that whatever voting method is used, the system is simple, accurate, verifiable, secure, accountable and transparent. The Commission shall ensure that the votes cast are counted, tabulated and the results announced promptly by the presiding officer.'),
            ('87', 'Electoral disputes', 'Parliament shall enact legislation to establish mechanisms for the timely settling of electoral disputes.'),
            ('88', 'Independent Electoral and Boundaries Commission', 'There is established the Independent Electoral and Boundaries Commission (IEBC). The Commission is responsible for conducting or supervising referenda and elections to any elective body established by this Constitution.'),
            ('89', 'Delimitation of electoral units', 'The boundaries of each constituency shall be such that the population is, as nearly as possible, equal to the population quota. The number of inhabitants of a constituency may be greater or less than the population quota to take account of geographical features, community interests, and means of communication.'),
            ('90', 'Allocation of party list seats', 'Elections for the seats in Parliament provided for under Articles 97(1)(c) and 98(1)(b),(c) and (d), and for the members of county assemblies under 177(1)(b) and (c), shall be on the basis of proportional representation using party lists.'),
            ('91', 'Basic requirements for political parties', 'Every political party shall have a national character as prescribed by an Act of Parliament, promote and uphold national unity, abide by the democratic principles of good governance, respect the right of all persons to participate in the political process, and respect and promote human rights and gender equality.'),
            ('92', 'Legislation on political parties', 'Parliament shall enact legislation to provide for the establishment and registration of political parties, the funding and accounts of political parties, and the formation of coalitions and mergers.'),
        ],
    },
    {
        'number': 7, 'title': 'The Legislature — Parliament',
        'subtitle': 'Articles 93–128',
        'overview': 'Establishes a bicameral Parliament consisting of the National Assembly and the Senate. Defines composition, roles, and procedures including law-making, oversight, and budget approval.',
        'articles': [
            ('93', 'Establishment of Parliament', 'There is established a Parliament of Kenya, which shall consist of the National Assembly and the Senate. The two Houses of Parliament shall perform their respective functions in accordance with this Constitution.'),
            ('94', 'Role of Parliament', 'The legislative authority of the Republic is derived from the people and, at the national level, is vested in and exercised by Parliament. Parliament shall protect this Constitution and promote the democratic governance of the Republic.'),
            ('95', 'Role of the National Assembly', 'The National Assembly represents the people, deliberates on and resolves issues of concern to the people, enacts legislation, determines the allocation of national revenue, appropriates funds for expenditure, exercises oversight over national revenue and expenditure, and reviews the conduct in office of the President and other State officers.'),
            ('96', 'Role of the Senate', 'The Senate represents the counties and protects the interests of counties and their governments. The Senate participates in the law-making function of Parliament by considering, debating and approving Bills concerning counties. The Senate determines the allocation of national revenue among counties and exercises oversight over national revenue allocated to county governments.'),
            ('97', 'Membership of the National Assembly', 'The National Assembly consists of 290 members elected for each constituency, 47 women each elected by voters of the counties, 12 members nominated by parliamentary political parties to represent special interests including youth, persons with disabilities and workers, and the Speaker who is an ex officio member.'),
            ('98', 'Membership of the Senate', 'The Senate consists of 47 members each elected by voters of the counties, 16 women members nominated by political parties, 2 members representing youth (one male, one female), 2 members representing persons with disabilities, and the Speaker who is an ex officio member.'),
            ('99', 'Qualifications and disqualifications for election as member of Parliament', 'A person is qualified for election if they are a citizen, are registered as a voter, satisfy any educational requirements, and are nominated by a political party or are an independent candidate.'),
            ('100', 'Promotion of representation of marginalised groups', 'Parliament shall enact legislation to promote the representation in Parliament of women, persons with disabilities, youth, ethnic and other minorities, and marginalised communities.'),
            ('101', 'Election of members of Parliament', 'A general election of members of Parliament shall be held on the second Tuesday in August in every fifth year.'),
            ('102', 'Term of Parliament', 'The term of each House of Parliament is five years, from the date of the first sitting after a general election.'),
            ('103', 'Vacation of office of member of Parliament', 'The office of a member of Parliament becomes vacant if the member dies, resigns, is recalled by the electorate, is disqualified, or is absent from eight consecutive sittings without permission.'),
            ('104', 'Right of recall', 'The electorate under Articles 97 and 98 have the right to recall the member of Parliament representing their constituency before the end of the term.'),
            ('105', 'Determination of questions of membership', 'The High Court shall hear and determine any question whether a person has been validly elected as a member of Parliament, or whether the seat of a member has become vacant.'),
            ('106', 'Speakers and Deputy Speakers of Parliament', 'There shall be a Speaker for each House of Parliament, who shall be elected by that House from among persons who are qualified to be elected as members of Parliament but are not such members.'),
            ('107', 'Presiding in Parliament', 'At any sitting of a House of Parliament, the Speaker, the Deputy Speaker, or another member elected by the House shall preside.'),
            ('108', 'Party leaders', 'There shall be a leader of the majority party and a leader of the minority party in each House of Parliament.'),
            ('109', 'Exercise of legislative powers', 'Parliament shall exercise its legislative power through Bills passed by Parliament and assented to by the President. A Bill may be introduced in either House, but a Bill not concerning county government may be introduced only in the National Assembly.'),
            ('110', 'Bills concerning county government', 'A Bill concerning county government is one that relates to the election of members of a county assembly or county executive, or a matter affecting the functions and financing of county governments.'),
            ('111', 'Special Bills concerning county governments', 'A special Bill concerning county governments shall be introduced in the National Assembly and then referred to the Senate.'),
            ('112', 'Ordinary Bills concerning county governments', 'An ordinary Bill concerning county government may originate in either House, and after being passed by that House shall be considered by the other House.'),
            ('113', 'Mediation committees', 'If one House passes a Bill and the other House rejects it or passes it with amendments to which the originating House objects, the Bill shall be referred to a mediation committee.'),
            ('114', 'Money Bills', 'A Money Bill may be introduced only in the National Assembly. A Money Bill is one that deals with taxation, borrowing, appropriation, or other public money matters.'),
            ('115', 'Presidential assent and referral', 'Within fourteen days of receipt of a Bill, the President shall either assent to the Bill or refer it back to Parliament for reconsideration. If the President refers a Bill back, Parliament may amend it or pass it a second time with a two-thirds majority, after which the President shall assent.'),
            ('116', 'Coming into force of laws', 'A law comes into force on the fourteenth day after its publication in the Kenya Gazette, unless the law provides for a different date.'),
            ('117', 'Powers, privileges and immunities', 'There shall be freedom of speech and debate in Parliament. No civil or criminal proceedings may be instituted against a member for words spoken in Parliament.'),
            ('118', 'Public access and participation', 'Parliament shall conduct its business in an open manner, and its sittings shall be open to the public. Parliament shall facilitate public participation in the legislative process.'),
            ('119', 'Right to petition Parliament', 'Every person has a right to petition Parliament to consider any matter within its authority, including enacting, amending or repealing any legislation.'),
            ('120', 'Official languages of Parliament', 'The official languages of Parliament are Kiswahili and English. The business of Parliament may be conducted in either language.'),
            ('121', 'Quorum', 'The quorum of each House is at least fifty members of the National Assembly and fifteen members of the Senate.'),
            ('122', 'Voting in Parliament', 'Except as otherwise provided, any question proposed for decision in either House shall be determined by a majority of the members present and voting. The Speaker shall have a casting vote.'),
            ('123', 'Decisions of Senate', 'On any matter other than a Bill, the Senate may resolve that a decision be taken by a vote of the delegations, where each county delegation has one vote.'),
            ('124', 'Committees and Standing Orders', 'Each House of Parliament may establish committees and shall make Standing Orders for the orderly conduct of its proceedings.'),
            ('125', 'Power to call for evidence', 'Parliament has the power to call any person to appear before it for the purpose of giving evidence or providing information.'),
            ('126', 'Public officers to attend Parliament', 'Cabinet Secretaries and other public officers may attend and participate in the proceedings of Parliament but may not vote.'),
            ('127', 'Parliamentary Service Commission', 'There is established the Parliamentary Service Commission, which shall provide services and facilities to ensure the efficient and effective functioning of Parliament.'),
            ('128', 'Clerks and staff of Parliament', 'There shall be a Clerk for each House of Parliament, appointed by the Parliamentary Service Commission. The offices of the Clerks are offices in the Parliamentary Service.'),
        ],
    },
    {
        'number': 8, 'title': 'The Executive',
        'subtitle': 'Articles 129–155',
        'overview': 'Establishes the Presidency, Deputy Presidency, Cabinet, and the national executive. Defines executive authority, election of the President, functions, impeachment, and formation of government.',
        'articles': [
            ('129', 'Principles of executive authority', 'Executive authority derives from the people of Kenya and shall be exercised in accordance with this Constitution. The executive shall respect, uphold and defend this Constitution.'),
            ('130', 'The National Executive', 'The national executive of the Republic comprises the President, the Deputy President, the Attorney-General, and the Cabinet.'),
            ('131', 'Authority of the President', 'The President is the Head of State and Government, the Commander-in-Chief of the Kenya Defence Forces, and the symbol of national unity. The President shall respect, uphold and safeguard this Constitution, safeguard the sovereignty of the Republic, and promote and enhance the unity of the nation.'),
            ('132', 'Functions of the President', 'The President shall address the opening of each newly elected Parliament, address a special sitting of Parliament once every year, and may address Parliament at any other time. The President shall nominate and appoint, with the approval of the National Assembly, Cabinet Secretaries and other State officers.'),
            ('133', 'Power of mercy', 'The President may exercise a power of mercy in accordance with the advice of the Advisory Committee on the Power of Mercy.'),
            ('134', 'Exercise of presidential powers during temporary incumbency', 'When the President is temporarily absent or incapacitated, the Deputy President may exercise the functions of the President.'),
            ('135', 'Decisions of the President', 'A decision of the President in writing shall be an instrument under seal. The President may delegate functions to other State officers.'),
            ('136', 'Election of the President', 'The President shall be elected by registered voters in a national election conducted in accordance with this Constitution and national legislation. A person qualifies for nomination if they are a citizen by birth, are qualified to stand for election as a member of Parliament, have been nominated by a political party or are an independent candidate, and have been nominated by at least two thousand voters from each of a majority of counties.'),
            ('137', 'Qualifications and disqualifications for election as President', 'A person shall not be qualified for election as President if they owe allegiance to a foreign state, are a public officer, or are of unsound mind.'),
            ('138', 'Procedure at presidential election', 'A candidate shall be declared elected as President if the candidate receives more than half of all the votes cast in the election, and at least twenty-five per cent of the votes cast in each of more than half of the counties.'),
            ('139', 'Death before assuming office', 'If a President-elect dies after being declared elected but before assuming office, the Deputy President-elect shall be sworn in as President.'),
            ('140', 'Questions as to validity of presidential election', 'A person may file a petition in the Supreme Court to challenge the election of the President-elect within seven days of the declaration of results. The Supreme Court shall hear and determine the petition within fourteen days.'),
            ('141', 'Assumption of office', 'The President-elect shall be sworn in on the first Tuesday following the fourteenth day after the date of the declaration of the result of the presidential election.'),
            ('142', 'Term of office of President', 'The President shall hold office for a term of five years beginning on the date of swearing-in, and may serve for a maximum of two terms.'),
            ('143', 'Protection from legal proceedings', 'Criminal proceedings shall not be instituted against a person holding the office of President during their tenure. Civil proceedings may be instituted, but shall be held in abeyance during the President\'s tenure.'),
            ('144', 'Removal of President on grounds of incapacity', 'The Deputy President or a member of the National Assembly supported by at least a quarter of members may move a resolution for investigation of the President\'s physical or mental capacity.'),
            ('145', 'Removal of President by impeachment', 'A member of the National Assembly may propose a motion for the impeachment of the President on grounds of gross violation of the Constitution, a crime under national or international law, or gross misconduct.'),
            ('146', 'Vacancy in the office of President', 'The office of President shall become vacant if the President dies, resigns, is removed under Article 144 or 145, or ceases to hold office under Article 142.'),
            ('147', 'Functions of the Deputy President', 'The Deputy President is the principal assistant of the President and shall perform the functions assigned by the President.'),
            ('148', 'Election and swearing in of Deputy President', 'A candidate for Deputy President shall be nominated by each candidate for President. The Deputy President-elect shall be sworn in before the President-elect.'),
            ('149', 'Vacancy in the office of Deputy President', 'Within fourteen days of a vacancy in the office of Deputy President, the President shall nominate a person to fill the vacancy, subject to approval by the National Assembly.'),
            ('150', 'Removal of Deputy President', 'The Deputy President may be removed from office on grounds of gross violation of the Constitution, a serious crime, or gross misconduct.'),
            ('151', 'Remuneration and benefits of President and Deputy President', 'The remuneration and benefits of the President and Deputy President shall be determined by the Salaries and Remuneration Commission.'),
            ('152', 'Cabinet', 'The Cabinet consists of the President, the Deputy President, the Attorney-General, and Cabinet Secretaries. The Cabinet shall assist the President in determining the general policy of the government.'),
            ('153', 'Decisions of Cabinet', 'A decision of the Cabinet shall be in writing. The Cabinet is collectively responsible to Parliament.'),
            ('154', 'Secretary to the Cabinet', 'There is established the office of the Secretary to the Cabinet, who is the chief executive officer of the Cabinet and shall be appointed by the President.'),
            ('155', 'Principal Secretaries', 'There is established the office of Principal Secretary, who is the administrative head of a State department. The President shall nominate a person for appointment as Principal Secretary, subject to approval by the National Assembly.'),
        ],
    },
    {
        'number': 9, 'title': 'The Judiciary',
        'subtitle': 'Articles 159–173',
        'overview': 'Establishes an independent judiciary, outlines the structure of courts from the Supreme Court down to subordinate courts, judicial authority, the Judicial Service Commission, and appointment of judges.',
        'articles': [
            ('159', 'Judicial authority', 'Judicial authority is derived from the people and vests in the courts and tribunals established by the Constitution. In exercising judicial authority, the courts shall be guided by the principles that justice shall be done to all, justice shall not be delayed, alternative forms of dispute resolution shall be promoted, justice shall be administered without undue regard to procedural technicalities, and the purpose of the Constitution shall be protected.'),
            ('160', 'Independence of the Judiciary', 'The Judiciary shall be independent and subject only to this Constitution and the law. No person or authority shall interfere with the Judiciary. The office of a judge shall not be abolished while the judge holds office.'),
            ('161', 'Judicial offices and officers', 'The Judiciary consists of the judges of the superior courts, magistrates, other judicial officers, and staff. The Judicial Service Commission is established to promote and facilitate the independence of the Judiciary.'),
            ('162', 'System of courts', 'The superior courts are the Supreme Court, the Court of Appeal, the High Court, and courts of equal status (the Employment and Labour Relations Court, and the Environment and Land Court). Parliament shall establish courts with the status of the High Court to hear matters relating to employment and labour relations, and the environment and land.'),
            ('163', 'Supreme Court', 'The Supreme Court consists of the Chief Justice, the Deputy Chief Justice, and five other judges. The Supreme Court has exclusive original jurisdiction to hear and determine presidential election petitions, and appellate jurisdiction to hear appeals from the Court of Appeal.'),
            ('164', 'Court of Appeal', 'The Court of Appeal consists of judges of the Court of Appeal, who shall elect a President of the Court from among themselves. The Court of Appeal has jurisdiction to hear appeals from the High Court and any other court or tribunal as prescribed by law.'),
            ('165', 'High Court', 'The High Court has unlimited original jurisdiction in criminal and civil matters. It has jurisdiction to determine whether a right or fundamental freedom in the Bill of Rights has been denied, violated, infringed or threatened. It also has jurisdiction to hear any question respecting the interpretation of this Constitution.'),
            ('166', 'Appointment of Chief Justice, Deputy Chief Justice and other judges', 'The Chief Justice and Deputy Chief Justice shall be appointed by the President, in accordance with the recommendation of the Judicial Service Commission, and subject to approval by the National Assembly.'),
            ('167', 'Tenure of office of the Chief Justice and other judges', 'A judge shall retire from office on attaining the age of seventy years, but may elect to retire at any time after attaining the age of sixty-five years. A judge shall serve a single term.'),
            ('168', 'Removal from office', 'A judge may be removed from office only on grounds of inability to perform their functions, a breach of a code of conduct, bankruptcy, incompetence, or gross misconduct. The process begins with a petition to the Judicial Service Commission.'),
            ('169', 'Subordinate courts', 'The subordinate courts are the Magistrates courts, the Kadhis courts, the Courts Martial, and any other court or local tribunal as may be established by an Act of Parliament.'),
            ('170', 'Kadhis Courts', 'There shall be a Chief Kadhi and such number of Kadhis as may be prescribed. The jurisdiction of a Kadhis court is limited to questions of Muslim law relating to personal status, marriage, divorce and inheritance.'),
            ('171', 'Judicial Service Commission', 'There is established the Judicial Service Commission. The Commission shall promote and facilitate the independence and accountability of the Judiciary and shall recommend persons to the President for appointment as judges.'),
            ('172', 'Functions of the Judicial Service Commission', 'The Judicial Service Commission shall recommend persons for judicial office, review and make recommendations on the conditions of service of judicial officers, appoint, receive complaints against, investigate and discipline registrars, magistrates, other judicial officers and staff.'),
            ('173', 'Judiciary Fund', 'There is established the Judiciary Fund, which shall be administered by the Chief Registrar. The Fund shall be used for administrative expenses of the Judiciary and such other purposes as may be necessary.'),
        ],
    },
    {
        'number': 10, 'title': 'Devolved Government',
        'subtitle': 'Articles 174–200',
        'overview': 'Establishes the objects and principles of devolved government, county governments (county assemblies and county executives), county legislation, powers and functions, and relationships between national and county governments.',
        'articles': [
            ('174', 'Objects of devolution', 'The objects of devolution are to promote democratic and accountable exercise of power, foster national unity, give powers of self-governance to the people, recognise the right of communities to manage their own affairs, protect minorities and marginalised communities, promote socio-economic development, and ensure equitable sharing of resources.'),
            ('175', 'Principles of devolved government', 'County governments shall have reliable sources of revenue to enable them to govern and deliver services effectively. No more than two-thirds of the members of representative bodies shall be of the same gender.'),
            ('176', 'County governments', 'There shall be a county government for each county, consisting of a county assembly and a county executive. Every county government shall decentralise its functions and services to the lowest level of administration.'),
            ('177', 'Membership of county assembly', 'A county assembly consists of members elected by voters of the wards, members representing marginalised groups (including persons with disabilities and youth), and the Speaker who is an ex officio member.'),
            ('178', 'Speaker of a county assembly', 'Each county assembly shall have a Speaker elected by the county assembly from among persons who are not members of the assembly.'),
            ('179', 'County executive committees', 'The executive authority of a county is vested in the county executive committee, consisting of the county governor, the deputy county governor, and members appointed by the county governor with the approval of the county assembly.'),
            ('180', 'Election of county governor and deputy county governor', 'The county governor shall be directly elected by the voters registered in the county. Each candidate for county governor shall nominate a person as a candidate for deputy governor.'),
            ('181', 'Removal of a county governor', 'A county governor may be removed from office on grounds of gross violation of the Constitution, commission of a crime, abuse of office, or gross misconduct.'),
            ('182', 'Vacancy in the office of county governor', 'The office of county governor shall become vacant if the governor dies, resigns, ceases to be eligible, is convicted of an offence, or is removed under Article 181.'),
            ('183', 'Functions of county executive committees', 'A county executive committee shall implement county legislation, implement national legislation within the county, manage and coordinate the functions of the county, and perform other functions assigned by the Constitution.'),
            ('184', 'Urban areas and cities', 'National legislation shall provide for the governance and management of urban areas and cities.'),
            ('185', 'Legislative authority of county assemblies', 'A county assembly may make any laws that are necessary for the effective performance of the functions of the county government.'),
            ('186', 'Respective functions of governments', 'The Fourth Schedule divides functions between the national and county governments. A function not assigned by this Constitution to a county is a function of the national government.'),
            ('187', 'Transfer of functions between governments', 'A function or power of government may be transferred from one level of government to the other by agreement.'),
            ('188', 'Boundaries of counties', 'The boundaries of a county may be altered only by a resolution of Parliament with the support of at least two-thirds of the members of each House, and in accordance with the recommendations of an independent commission.'),
            ('189', 'Cooperation between governments', 'Government at either level shall perform its functions and exercise its powers in a manner that respects the functional and institutional integrity of the other level.'),
            ('190', 'Support for county governments', 'Parliament shall by legislation ensure that county governments have adequate support to enable them to perform their functions.'),
            ('191', 'Conflict of laws', 'National legislation prevails over county legislation if it applies uniformly throughout Kenya and is aimed at maintaining national economic unity, security, or common market standards.'),
            ('192', 'Suspension of county governments', 'The President may suspend a county government in cases of emergency or a situation arising out of a state of emergency, or for other compelling reasons.'),
            ('193', 'Qualifications for election as member of county assembly', 'A person is disqualified from being elected as a member of a county assembly if they are a State officer or a member of a county public service.'),
            ('194', 'Vacation of office of member of county assembly', 'The office of a member of a county assembly becomes vacant if the member dies, resigns, is recalled, is disqualified, or is absent from eight consecutive sittings.'),
            ('195', 'County assembly power to summon witnesses', 'A county assembly has the power to summon any person to appear before it for the purpose of giving evidence or providing information.'),
            ('196', 'Public participation and county assembly powers', 'A county assembly shall conduct its business in an open manner and shall facilitate public participation in the legislative process.'),
            ('197', 'County assembly committees', 'A county assembly may establish committees for the better discharge of its functions.'),
            ('198', 'County assembly standing orders', 'A county assembly shall adopt Standing Orders for the orderly conduct of its proceedings.'),
            ('199', 'County assembly privileges and immunities', 'There shall be freedom of speech and debate in county assemblies. Members of county assemblies shall have the same privileges and immunities as members of Parliament.'),
            ('200', 'Legislation on Chapter Ten', 'Parliament shall enact legislation to provide for all matters necessary or convenient to give effect to this Chapter.'),
        ],
    },
    {
        'number': 11, 'title': 'Public Finance',
        'subtitle': 'Articles 201–226',
        'overview': 'Establishes principles of public finance, the Consolidated Fund, the Revenue Fund, procurement rules, the Controller of Budget, the Auditor-General, the Central Bank, and the Salaries and Remuneration Commission.',
        'articles': [
            ('201', 'Principles of public finance', 'The following principles shall guide public finance: openness and accountability, public participation, equitable sharing of the burden of taxation, equitable allocation of resources, equitable sharing of revenue, and prudent and responsible use of public funds.'),
            ('202', 'Equitable sharing of national revenue', 'Revenue raised nationally shall be shared equitably among the national and county governments. County governments may be given additional allocations from the national government\'s share.'),
            ('203', 'Equitable share and other financial laws', 'The criteria for determining equitable shares include the national interest, public debt, the needs of the national government, the fiscal capacity and efficiency of county governments, developmental needs, and the need for affirmative action.'),
            ('204', 'Equalisation Fund', 'The Equalisation Fund shall be used to provide basic services including water, roads, health facilities and electricity to marginalised areas. The Fund shall be administered by the national government.'),
            ('205', 'Consultation on financial legislation affecting counties', 'When a Bill that includes provisions dealing with the sharing of revenue or any financial matter concerning counties is published, the Commission on Revenue Allocation shall be consulted.'),
            ('206', 'Consolidated Fund and other public funds', 'There is established the Consolidated Fund into which shall be paid all money raised or received by or on behalf of the national government.'),
            ('207', 'Revenue Funds for county governments', 'There shall be a Revenue Fund for each county government, into which shall be paid all money raised or received by or on behalf of the county government.'),
            ('208', 'Contingencies Fund', 'There is established the Contingencies Fund, which shall be used for urgent and unforeseen expenditure.'),
            ('209', 'Power to impose taxes and charges', 'Only the national government may impose income tax, value added tax, customs duties, and excise tax. Both the national government and county governments may impose property rates and entertainment taxes.'),
            ('210', 'Imposition of tax', 'No tax or licensing fee may be imposed, waived or varied except as provided by legislation.'),
            ('211', 'Borrowing by national government', 'Parliament may, by legislation, authorise the national government to borrow money, and shall prescribe the terms on which the government may borrow.'),
            ('212', 'Borrowing by counties', 'A county government may borrow only if the national government guarantees the loan and with the approval of the county assembly.'),
            ('213', 'Loan guarantees by national government', 'An Act of Parliament shall provide for the guarantees of loans by the national government.'),
            ('214', 'Public debt', 'The public debt is a charge on the Consolidated Fund, but an Act of Parliament may provide for charging all or part of the public debt to other public funds.'),
            ('215', 'Commissions on revenue allocation', 'The Commission on Revenue Allocation shall make recommendations concerning the basis for the equitable sharing of revenue raised by the national government between the national and county governments.'),
            ('216', 'Commission on Revenue Allocation', 'The Commission on Revenue Allocation shall consist of a chairperson appointed by the President, the Principal Secretary in the Ministry of Finance, and five other members nominated by political parties.'),
            ('217', 'Division of revenue', 'Once every five years, the Senate shall determine the basis for allocating among the counties the share of national revenue allocated to the counties.'),
            ('218', 'Annual Division of Revenue Bill', 'The Division of Revenue Bill shall divide the revenue raised nationally among the national and county levels of government.'),
            ('219', 'Transfer of equitable share', 'A county\'s share of revenue raised by the national government shall be transferred to the county without undue delay and without deduction.'),
            ('220', 'Form and content of budgets', 'Budgets of the national and county governments shall contain estimates of revenue and expenditure, a summary of actual revenue and expenditure for the preceding years, and a statement of assets and liabilities.'),
            ('221', 'Budget estimates', 'At least two months before the end of each financial year, the Cabinet Secretary responsible for finance shall submit to the National Assembly estimates of the revenue and expenditure of the national government.'),
            ('222', 'Expenditure before annual budget is passed', 'If the Appropriation Bill is not assented to by the beginning of a financial year, Parliament may authorise withdrawal of money for up to four months.'),
            ('223', 'Supplementary appropriation', 'The national government may spend money not appropriated if the amount is vired from another item, or if the expenditure is authorised by an Act of Parliament or by the Cabinet Secretary for finance.'),
            ('224', 'County appropriation Bills', 'A county assembly shall consider and pass an appropriation Bill before the commencement of a financial year.'),
            ('225', 'Financial control', 'Parliament shall enact legislation to provide for the preparation and submission of accounts of the national and county governments, the audit of those accounts, and the protection of public money.'),
            ('226', 'Accounts and audit of public entities', 'An Act of Parliament shall provide for the keeping of financial records and the auditing of accounts of all governments and public entities.'),
        ],
    },
    {
        'number': 12, 'title': 'The Public Service',
        'subtitle': 'Articles 232–240',
        'overview': 'Establishes the values and principles of public service, the Public Service Commission, the Teachers Service Commission, the National Police Service, and the Kenya Defence Forces.',
        'articles': [
            ('232', 'Values and principles of public service', 'The values and principles of public service include high standards of professional ethics, efficient and effective use of resources, responsive and prompt service delivery, involvement of the people, accountability, transparency, and fair competition and merit in appointments.'),
            ('233', 'The Public Service Commission', 'There is established the Public Service Commission. The Commission shall establish and abolish offices in the public service, appoint persons to hold those offices, and exercise disciplinary control over public officers.'),
            ('234', 'Functions and powers of the Public Service Commission', 'The Public Service Commission may delegate some of its functions to any person or body. The Commission shall evaluate and report on the extent to which the values and principles referred to in Article 232 are complied with.'),
            ('235', 'Staffing of county governments', 'County governments are responsible for the recruitment and management of their own staff. The Public Service Commission shall provide standards for human resource management.'),
            ('236', 'Protection of public officers', 'A public officer shall not be victimised or discriminated against for having performed their functions in accordance with this Constitution or any law.'),
            ('237', 'Teachers Service Commission', 'There is established the Teachers Service Commission. The Commission shall register trained teachers, recruit and employ registered teachers, assign teachers for service, and promote and transfer teachers.'),
            ('238', 'Principles of national security', 'National security is the protection against internal and external threats to Kenya\'s territorial integrity, sovereignty, its people, their rights and freedoms, and their way of life. National security shall be pursued in compliance with the law and with the utmost respect for human rights.'),
            ('239', 'National security organs', 'The national security organs are the Kenya Defence Forces, the National Intelligence Service, and the National Police Service. Their primary objective is to promote and guarantee national security.'),
            ('240', 'Establishment of the National Security Council', 'There is established the National Security Council consisting of the President, the Deputy President, the Cabinet Secretaries responsible for defence, foreign affairs and internal security, and other members as prescribed.'),
            ('241', 'Kenya Defence Forces', 'The Kenya Defence Forces consist of the Kenya Army, the Kenya Air Force, and the Kenya Navy. The KDF is responsible for the defence and protection of the sovereignty and territorial integrity of the Republic.'),
            ('242', 'National Intelligence Service', 'There is established the National Intelligence Service, responsible for security intelligence and counter-intelligence.'),
            ('243', 'National Police Service', 'There is established the National Police Service, consisting of the Kenya Police Service and the Administration Police Service. The NPS shall strive for the highest standards of professionalism and discipline, prevent corruption, and comply with constitutional standards of human rights.'),
            ('244', 'Objects and functions of the National Police Service', 'The NPS shall prevent crime, investigate crime, maintain law and order, and protect life and property. The Inspector-General of Police exercises command over the NPS.'),
            ('245', 'Command of the National Police Service', 'The Inspector-General shall exercise independent command over the National Police Service. No person may give a direction to the Inspector-General with respect to the investigation of any particular offence.'),
            ('246', 'National Police Service Commission', 'There is established the National Police Service Commission, which shall recruit and appoint persons to hold offices in the NPS, confirm appointments, and determine promotions and transfers.'),
            ('247', 'Independent Policing Oversight Authority', 'There is established the Independent Policing Oversight Authority (IPOA), which shall investigate any complaints related to disciplinary or criminal offences committed by any member of the NPS.'),
        ],
    },
    {
        'number': 13, 'title': 'Leadership and Integrity',
        'subtitle': 'Articles 73–80, 260',
        'overview': 'Sets the standards for State officers and public officers. Establishes Chapter Six on leadership and integrity governing conduct, conflicts of interest, and financial probity of all public officials.',
        'articles': [
            ('73', 'Responsibilities of leadership', 'Authority assigned to a State officer is a public trust to be exercised in a manner that is consistent with the purposes and objects of this Constitution, demonstrates respect for the people, brings honour to the nation, promotes public confidence, and does not discredit the office.'),
            ('74', 'Oath of office of State officers', 'Before assuming a State office, a person shall take and subscribe the oath or affirmation prescribed by this Constitution or an Act of Parliament.'),
            ('75', 'Conduct of State officers', 'A State officer shall behave, whether in public and official life, in private life, or in association with other persons, in a manner that avoids any conflict between personal interests and public or official duties, compromising any public or official interest, or demeaning the office.'),
            ('76', 'Financial probity of State officers', 'A gift or donation to a State officer on a public or official occasion is a gift or donation to the Republic. A State officer shall not maintain a bank account outside Kenya or seek a loan that would compromise their integrity.'),
            ('77', 'Restriction on activities of State officers', 'A full-time State officer shall not participate in any other gainful employment. Any appointed State officer shall not hold office in a political party.'),
            ('78', 'Citizenship and leadership', 'A person is not eligible for election or appointment to a State office unless the person is a citizen of Kenya.'),
            ('79', 'Legislation on leadership', 'Parliament shall enact legislation to establish a code of conduct for State officers, establish an independent ethics and anti-corruption commission, and make provision for the investigation of allegations of contravention of the leadership and integrity code.'),
            ('80', 'Legislation on elections', 'Parliament shall enact legislation to provide for the conduct of elections and referenda, the registration of voters, and the nomination of candidates.'),
        ],
    },
    {
        'number': 14, 'title': 'Commissions and Independent Offices',
        'subtitle': 'Articles 248–254',
        'overview': 'Establishes independent constitutional commissions and their objects. Covers the Kenya National Human Rights and Equality Commission, National Land Commission, Independent Electoral and Boundaries Commission, and others.',
        'articles': [
            ('248', 'Application of Chapter', 'This Chapter applies to the commissions and independent offices specified, including the Kenya National Human Rights and Equality Commission, the National Land Commission, the Independent Electoral and Boundaries Commission, the Parliamentary Service Commission, the Judicial Service Commission, the Commission on Revenue Allocation, the Public Service Commission, the Salaries and Remuneration Commission, the Teachers Service Commission, and the National Police Service Commission.'),
            ('249', 'Objects, authority and funding of commissions', 'The objects of the commissions are to protect the sovereignty of the people, secure the observance of democratic values, and promote constitutionalism. The commissions are subject only to this Constitution and the law, and are independent. Parliament shall allocate adequate funds to enable each commission to perform its functions.'),
            ('250', 'Composition of commissions', 'Each commission shall consist of at least three, but not more than nine, members. The chairperson and each member of a commission shall serve for a single term of six years.'),
            ('251', 'Removal from office', 'A member of a commission may be removed from office only for serious violation of this Constitution, a serious crime, gross misconduct, physical or mental incapacity, incompetence, or bankruptcy.'),
            ('252', 'General functions and powers', 'Each commission shall conduct its affairs in a manner that is transparent and shall publish regular reports. A commission may issue summons and may require that statements be given under oath.'),
            ('253', 'Incorporation of commissions', 'Each commission has the power to acquire, hold and dispose of property, to enter into contracts, and to sue and be sued in its own name.'),
            ('254', 'Reporting by commissions', 'Each commission shall, within three months of the end of each financial year, submit a report to the President and to Parliament.'),
        ],
    },
    {
        'number': 15, 'title': 'Amendment of the Constitution',
        'subtitle': 'Articles 255–257',
        'overview': 'Provides the procedure for amending the Constitution, distinguishing between amendments by parliamentary vote, amendments by popular initiative, and amendments requiring a referendum.',
        'articles': [
            ('255', 'Amendment of this Constitution', 'A proposed amendment to this Constitution shall be enacted in accordance with Article 256 or 257, and passed in accordance with this Article. An amendment to the supremacy of this Constitution, the territory of Kenya, the sovereignty of the people, the national values and principles of governance, the Bill of Rights, the term of office of the President, the independence of the Judiciary, the functions of Parliament, or the objects and principles of devolved government shall require approval through a referendum.'),
            ('256', 'Amendment by parliamentary initiative', 'A Bill to amend the Constitution may be introduced in either House of Parliament. If the Bill relates to a matter that requires a referendum under Article 255, it shall be submitted to the people in a referendum within ninety days.'),
            ('257', 'Amendment by popular initiative', 'An amendment may be proposed by a popular initiative signed by at least one million registered voters. The Independent Electoral and Boundaries Commission shall verify the signatures and submit the draft Bill to each county assembly for consideration. If approved by a majority of county assemblies, it shall be introduced in Parliament.'),
        ],
    },
    {
        'number': 16, 'title': 'General Provisions',
        'subtitle': 'Articles 258–264',
        'overview': 'Contains provisions on enforcement of the Constitution, interpretation, definitions, consequential provisions, repeals, and the transitional and consequential provisions in the Sixth Schedule.',
        'articles': [
            ('258', 'Enforcement of this Constitution', 'Every person has the right to institute court proceedings claiming that this Constitution has been contravened or is threatened with contravention.'),
            ('259', 'Construing this Constitution', 'This Constitution shall be interpreted in a manner that promotes its purposes, values and principles, advances the rule of law, and contributes to good governance. The provisions of this Constitution shall be construed according to the doctrine that the law is always speaking.'),
            ('260', 'Interpretation', 'In this Constitution, unless the context otherwise requires, words and expressions have the meanings assigned. The definition section clarifies key terms including "adult," "county," "effective date," "public officer," "State," "State office," and "State officer."'),
            ('261', 'Consequential legislation', 'Parliament shall enact any legislation required by this Constitution to be enacted to govern a particular matter within the period specified. If Parliament fails to enact legislation within the period, any person may petition the High Court.'),
            ('262', 'Transitional and consequential provisions', 'The transitional and consequential provisions set out in the Sixth Schedule shall take effect on the effective date.'),
            ('263', 'Effective Date', 'This Constitution shall come into force on its promulgation by the President or on the expiry of the period of fourteen days from the publication in the Gazette of the final result of the referendum ratifying this Constitution.'),
            ('264', 'Repeal of previous constitution', 'Subject to the Sixth Schedule, the Constitution of the Republic of Kenya, 1969, as amended, is repealed.'),
        ],
    },
    {
        'number': 17, 'title': 'Transitional and Consequential Provisions',
        'subtitle': 'Sixth Schedule, Sections 1–42',
        'overview': 'Deals with the transition from the old constitutional order to the new one. Covers continuation of laws, offices, and institutions; the process for devolution; and dissolution of previous bodies.',
        'articles': [
            ('S6-1', 'Interpretation', 'In this Schedule, unless the context requires otherwise, "effective date" means the date on which this Constitution comes into force.'),
            ('S6-2', 'Transitional provisions', 'All laws in force immediately before the effective date shall continue in force and shall be construed with the alterations, adaptations, qualifications and exceptions necessary to bring them into conformity with this Constitution.'),
            ('S6-3', 'Continuation of offices', 'Except as otherwise provided, a person who immediately before the effective date held or was acting in an office established by the former Constitution shall continue to hold or act in that office.'),
            ('S6-4', 'National assembly and Senate', 'Until the first general elections after the effective date, the National Assembly and Senate shall consist of the persons elected or nominated at the first elections under this Constitution.'),
            ('S6-5', 'First elections', 'The first elections for the President, members of Parliament, county governors and members of county assemblies under this Constitution shall be held within sixty days of the dissolution of the existing National Assembly.'),
            ('S6-6', 'Devolution', 'The laws relating to devolved government shall be enacted within eighteen months of the effective date. The national government shall facilitate the establishment of county governments.'),
            ('S6-7', 'Legislative and executive powers', 'Until county governments are fully established, the national government shall continue to exercise all legislative and executive powers.'),
        ],
    },
    {
        'number': 18, 'title': 'Schedules to the Constitution',
        'subtitle': 'First to Sixth Schedule',
        'overview': 'Contains the six schedules: National Symbols, Counties, Oaths, Distribution of Functions, Legislation to be Enacted, and Transitional Provisions.',
        'articles': [],
    },
]


SCHEDULES = [
    {
        'number': 1,
        'title': 'National Symbols',
        'content': 'The First Schedule contains the national symbols of the Republic of Kenya:\n\n1. The National Flag — A tricolour of black, red and green with white fimbriations and a Maasai shield with two crossed spears in the centre.\n\n2. The National Anthem — "Ee Mungu Nguvu Yetu" (O God of All Creation) with verses in Kiswahili and English.\n\n3. The Coat of Arms — Features two lions holding Maasai spears and a shield bearing the national colours, with a cockerel holding an axe, all atop a representation of Mount Kenya.\n\n4. The Public Seal — The official seal of the Republic used on all State documents.',
    },
    {
        'number': 2,
        'title': 'Counties of Kenya',
        'content': 'The Second Schedule lists the forty-seven counties of Kenya as established under Article 6:\n\n1. Mombasa · 2. Kwale · 3. Kilifi · 4. Tana River · 5. Lamu · 6. Taita Taveta · 7. Garissa · 8. Wajir · 9. Mandera · 10. Marsabit · 11. Isiolo · 12. Meru · 13. Tharaka Nithi · 14. Embu · 15. Kitui · 16. Machakos · 17. Makueni · 18. Nyandarua · 19. Nyeri · 20. Kirinyaga · 21. Murang\'a · 22. Kiambu · 23. Turkana · 24. West Pokot · 25. Samburu · 26. Trans Nzoia · 27. Uasin Gishu · 28. Elgeyo Marakwet · 29. Nandi · 30. Baringo · 31. Laikipia · 32. Nakuru · 33. Narok · 34. Kajiado · 35. Kericho · 36. Bomet · 37. Kakamega · 38. Vihiga · 39. Bungoma · 40. Busia · 41. Siaya · 42. Kisumu · 43. Homa Bay · 44. Migori · 45. Kisii · 46. Nyamira · 47. Nairobi.',
    },
    {
        'number': 3,
        'title': 'National Oaths and Affirmations',
        'content': 'The Third Schedule prescribes the oaths and affirmations of office for constitutional office holders:\n\n1. The Presidential Oath — Swearing allegiance to the Republic, upholding the Constitution, and serving the people of Kenya faithfully.\n\n2. The Oath for the Deputy President, Cabinet Secretaries, Principal Secretaries, and other State officers.\n\n3. The Judicial Oath — Swearing to administer justice without fear, favour, affection or ill-will.\n\n4. The Oath for Members of Parliament — Swearing true allegiance to the Republic and to uphold and defend the Constitution.',
    },
    {
        'number': 4,
        'title': 'Distribution of Functions',
        'content': 'The Fourth Schedule distributes functions between the national government and county governments:\n\n**National Government Functions:**\n- Foreign affairs and international trade\n- Defence and national security\n- Police services\n- Courts and judicial services\n- National economic policy and planning\n- Monetary policy and currency\n- Immigration and citizenship\n- National infrastructure (trunk roads, railways, ports, airports)\n- Energy policy\n- Higher education and universities\n- National health policy and referral health facilities\n- National elections\n\n**County Government Functions:**\n- Agriculture, livestock and fisheries\n- County health services (excluding referral facilities)\n- County transport and roads\n- Pre-primary education and childcare\n- County planning and development\n- Trade development and regulation within the county\n- County public works and services\n- Firefighting and disaster management\n- Control of drugs and pornography\n- Cultural activities, public entertainment and public amenities\n- County parks, recreation and sports facilities\n- County taxation and licensing',
    },
    {
        'number': 5,
        'title': 'Legislation to be Enacted by Parliament',
        'content': 'The Fifth Schedule lists all legislation required to be enacted by Parliament under the Constitution, with deadlines:\n\n**Within 18 months:**\n- Legislation on the election and registration of voters\n- Legislation on political parties\n- Legislation on the Independent Electoral and Boundaries Commission\n- Legislation on citizenship\n- Legislation on the Kenya National Human Rights and Equality Commission\n- Legislation on the National Land Commission\n\n**Within 2 years:**\n- Legislation on the administration of Parliament\n- Legislation on the Judicial Service Commission\n- Legislation on the county governments\n- Legislation on the National Police Service\n- Legislation on the Kenya Defence Forces\n- Legislation on public finance management\n\n**Within 3 years:**\n- Legislation on leadership and integrity\n- Legislation on the environment and land\n- Legislation on consumer protection\n- Legislation on fair administrative action\n\n**Within 5 years:**\n- Legislation on community land\n- Legislation on the regulation of land use and property\n- Legislation on agreements relating to natural resources',
    },
    {
        'number': 6,
        'title': 'Transitional and Consequential Provisions',
        'content': 'The Sixth Schedule provides for the transition from the former Constitution to the Constitution of Kenya, 2010:\n\n1. It preserves all existing laws and provides that they continue with necessary adaptations to conform to the new Constitution.\n\n2. The first elections under the new Constitution were held within 60 days of the dissolution of the existing National Assembly.\n\n3. The national executive established under the new Constitution assumed office after the first elections.\n\n4. The Judiciary transitioned to the new structure of courts, with existing judges continuing in service.\n\n5. County governments were established within 18 months of the effective date, with the national government facilitating the transition.\n\n6. The Transition Authority oversaw the transfer of functions from the national government to county governments.\n\n7. All State officers holding office under the former Constitution continued in office until the first elections under the new Constitution, unless they chose to retire.',
    },
]


class Command(BaseCommand):
    help = 'Load the Constitution of Kenya, 2010 into the database.'

    def handle(self, *args, **options):
        self.stdout.write('Loading Constitution of Kenya, 2010...')

        Chapter.objects.all().delete()
        Article.objects.all().delete()
        Schedule.objects.all().delete()

        for idx, ch_data in enumerate(CONSTITUTION):
            chapter = Chapter.objects.create(
                number=ch_data['number'],
                title=ch_data['title'],
                subtitle=ch_data.get('subtitle', ''),
                overview=ch_data.get('overview', ''),
                order=idx,
            )
            for art_idx, (art_num, art_title, art_content) in enumerate(ch_data['articles']):
                Article.objects.create(
                    chapter=chapter,
                    number=art_num,
                    title=art_title,
                    content=art_content,
                    order=art_idx,
                )
            self.stdout.write(f'  Chapter {chapter.number}: {chapter.title} ({chapter.article_count} articles)')

        for idx, s_data in enumerate(SCHEDULES):
            Schedule.objects.create(
                number=s_data['number'],
                title=s_data['title'],
                content=s_data['content'],
                order=idx,
            )
            self.stdout.write(f'  Schedule {s_data["number"]}: {s_data["title"]}')

        self.stdout.write(self.style.SUCCESS(
            f'Loaded {Chapter.objects.count()} chapters, {Article.objects.count()} articles, and {Schedule.objects.count()} schedules.'
        ))
