# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('certificate_type', models.CharField(max_length=100)),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('assessment_year', models.PositiveSmallIntegerField()),
                ('tax_type', models.CharField(choices=[('income_tax', 'Income Tax (PAYE)'), ('corporate_tax', 'Corporate Tax'), ('vat', 'Value Added Tax'), ('excise_duty', 'Excise Duty'), ('customs_duty', 'Customs Duty'), ('capital_gains', 'Capital Gains Tax'), ('withholding', 'Withholding Tax'), ('turnover', 'Turnover Tax'), ('rental_income', 'Rental Income Tax'), ('other', 'Other')], max_length=30)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_assessed', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('tax_type', models.CharField(choices=[('income_tax', 'Income Tax (PAYE)'), ('corporate_tax', 'Corporate Tax'), ('vat', 'Value Added Tax'), ('excise_duty', 'Excise Duty'), ('customs_duty', 'Customs Duty'), ('capital_gains', 'Capital Gains Tax'), ('withholding', 'Withholding Tax'), ('turnover', 'Turnover Tax'), ('rental_income', 'Rental Income Tax'), ('other', 'Other')], max_length=30)),
                ('tax_period', models.CharField(max_length=50)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
