# Generated by Django 5.2.4 on 2026-05-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('police', 'Police'), ('fire', 'Fire'), ('ambulance', 'Ambulance'), ('other', 'Other')], default='police', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contacts', to='counties.county')),
            ],
            options={
                'ordering': ['service_type', 'name'],
                'indexes': [models.Index(fields=['service_type', 'is_active'], name='emergency_e_service_8e53a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('emergency_type', models.CharField(choices=[('police', 'Police'), ('fire', 'Fire'), ('ambulance', 'Ambulance'), ('disaster', 'Disaster'), ('accident', 'Accident'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('dispatched', 'Dispatched'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['reference'], name='emergency_e_referen_82f493_idx'), models.Index(fields=['status'], name='emergency_e_status_4bac3a_idx'), models.Index(fields=['emergency_type'], name='emergency_e_emergen_cd3e72_idx')],
            },
        ),
    ]
