# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('counties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_au_created_848def_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('alien_id', 'Alien ID'), ('military_id', 'Military ID'), ('birth_certificate', 'Birth Certificate'), ('service_id', 'Service ID Card')], default='national_id', max_length=20)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('administrator', 'Administrator'), ('agency_staff', 'Agency Staff'), ('developer', 'Developer'), ('auditor', 'Auditor'), ('support', 'Support Staff')], default='citizen', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='counties.county')),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='counties.subcounty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='counties.ward')),
            ],
            options={
                'indexes': [models.Index(fields=['id_number'], name='accounts_pr_id_numb_91e909_idx'), models.Index(fields=['phone'], name='accounts_pr_phone_a8479a_idx')],
            },
        ),
    ]
