# Generated by Django 5.2.4 on 2026-05-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
