# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('tender_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('procurement_method', models.CharField(default='open_tender', max_length=100)),
                ('closing_date', models.DateTimeField()),
                ('bid_bond_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_review', 'Under Review'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='ministries.ministry')),
            ],
            options={
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('awarded_to', models.CharField(max_length=255)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(default='supply', max_length=100)),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='procurement.tendernotice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('bid_bond_reference', models.CharField(blank=True, max_length=100)),
                ('technical_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('financial_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.tendernotice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
