# Generated by Django 5.2.4 on 2026-05-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionalFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('mandate_ref', models.CharField(help_text='e.g. Fourth Schedule Part 2, Section 1', max_length=100)),
                ('icon', models.CharField(default='Building', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='constitutional_function',
            field=models.ForeignKey(blank=True, help_text='County government function this service fulfills (Fourth Schedule)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.constitutionalfunction'),
        ),
    ]
