# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('license_type', models.CharField(choices=[('single_business', 'Single Business Permit'), ('general_trade', 'General Trade License'), ('manufacturing', 'Manufacturing License'), ('hospitality', 'Hospitality & Entertainment'), ('health_facility', 'Health Facility License'), ('transport', 'Transport Business License'), ('professional', 'Professional Services License'), ('financial', 'Financial Services License'), ('import_export', 'Import/Export License'), ('other', 'Other')], max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=15)),
                ('number_of_employees', models.PositiveIntegerField(default=0)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_licenses', to='counties.county')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('certification_name', models.CharField(max_length=255)),
                ('certification_type', models.CharField(choices=[('medical', 'Medical'), ('legal', 'Legal'), ('engineering', 'Engineering'), ('accounting', 'Accounting'), ('architecture', 'Architecture'), ('teaching', 'Teaching'), ('real_estate', 'Real Estate'), ('surveying', 'Surveying'), ('other', 'Other')], default='other', max_length=30)),
                ('issuing_body', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
