# Generated by Django 5.2.4 on 2026-05-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth 2.0'), ('basic', 'Basic Auth')], default='api_key', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='integration_code_62d05a_idx'), models.Index(fields=['is_active'], name='integration_is_acti_06f795_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('data_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exchanges', to='integration.externalsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=15)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integration.dataexchange')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataexchange',
            index=models.Index(fields=['system', 'status'], name='integration_system__b59004_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexchange',
            index=models.Index(fields=['direction'], name='integration_directi_1743d4_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['exchange', 'status'], name='integration_exchang_5569b0_idx'),
        ),
    ]
