# Generated by Django 5.2.4 on 2026-05-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('indexed_data', models.JSONField(blank=True, default=dict)),
                ('last_indexed', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_indexes', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Search Indexes',
                'ordering': ['-last_indexed'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='search_sear_content_97a989_idx'), models.Index(fields=['last_indexed'], name='search_sear_last_in_53c1af_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_search_index_entry')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='search_sear_created_819524_idx')],
            },
        ),
    ]
