# Generated by Django 5.2.4 on 2026-05-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('house', models.CharField(choices=[('national_assembly', 'National Assembly'), ('senate', 'Senate')], default='national_assembly', max_length=30)),
                ('sponsor', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('first_reading', 'First Reading'), ('second_reading', 'Second Reading'), ('committee', 'Committee Stage'), ('report', 'Report Stage'), ('third_reading', 'Third Reading'), ('passed', 'Passed'), ('assented', 'Assented to'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('date_introduced', models.DateField(blank=True, null=True)),
                ('date_passed', models.DateField(blank=True, null=True)),
                ('date_assented', models.DateField(blank=True, null=True)),
                ('full_text_url', models.URLField(blank=True, max_length=1000)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_introduced', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateField(db_index=True)),
                ('summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('full_text_url', models.URLField(blank=True, max_length=1000)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Hansard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(db_index=True)),
                ('house', models.CharField(choices=[('national_assembly', 'National Assembly'), ('senate', 'Senate')], max_length=30)),
                ('sitting_number', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['house', '-date'], name='legislature_house_947098_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParliamentarySitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('house', models.CharField(choices=[('national_assembly', 'National Assembly'), ('senate', 'Senate')], max_length=30)),
                ('session', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('minutes_url', models.URLField(blank=True, max_length=1000)),
                ('order_paper_url', models.URLField(blank=True, max_length=1000)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['house', '-date'], name='legislature_house_3d75b3_idx')],
            },
        ),
    ]
