COUNTIES = [
    ('001', 'Mombasa'),
    ('002', 'Kwale'),
    ('003', 'Kilifi'),
    ('004', 'Tana River'),
    ('005', 'Lamu'),
    ('006', 'Taita Taveta'),
    ('007', 'Garissa'),
    ('008', 'Wajir'),
    ('009', 'Mandera'),
    ('010', 'Marsabit'),
    ('011', 'Isiolo'),
    ('012', 'Meru'),
    ('013', 'Tharaka Nithi'),
    ('014', 'Embu'),
    ('015', 'Kitui'),
    ('016', 'Machakos'),
    ('017', 'Makueni'),
    ('018', 'Nyandarua'),
    ('019', 'Nyeri'),
    ('020', 'Kirinyaga'),
    ('021', 'Murang\'a'),
    ('022', 'Kiambu'),
    ('023', 'Turkana'),
    ('024', 'West Pokot'),
    ('025', 'Samburu'),
    ('026', 'Trans Nzoia'),
    ('027', 'Uasin Gishu'),
    ('028', 'Elgeyo Marakwet'),
    ('029', 'Nandi'),
    ('030', 'Baringo'),
    ('031', 'Laikipia'),
    ('032', 'Nakuru'),
    ('033', 'Narok'),
    ('034', 'Kajiado'),
    ('035', 'Kericho'),
    ('036', 'Bomet'),
    ('037', 'Kakamega'),
    ('038', 'Vihiga'),
    ('039', 'Bungoma'),
    ('040', 'Busia'),
    ('041', 'Siaya'),
    ('042', 'Kisumu'),
    ('043', 'Homa Bay'),
    ('044', 'Migori'),
    ('045', 'Kisii'),
    ('046', 'Nyamira'),
    ('047', 'Nairobi'),
]

MINISTRIES = [
    'Office of the President',
    'Office of the Deputy President',
    'Office of the Prime Cabinet Secretary',
    'Ministry of Interior and National Administration',
    'Ministry of Defence',
    'Ministry of Foreign and Diaspora Affairs',
    'Ministry of Finance and National Planning',
    'Ministry of Health',
    'Ministry of Education',
    'Ministry of Agriculture and Livestock Development',
    'Ministry of Water, Sanitation and Irrigation',
    'Ministry of Energy and Petroleum',
    'Ministry of Transport and Infrastructure',
    'Ministry of Lands, Public Works, Housing and Urban Development',
    'Ministry of Information, Communications and the Digital Economy',
    'Ministry of Trade, Investment and Industry',
    'Ministry of Labour and Social Protection',
    'Ministry of Environment, Climate Change and Forestry',
    'Ministry of Tourism and Wildlife',
    'Ministry of Mining, Blue Economy and Maritime Affairs',
    'Ministry of Sports, Culture and Heritage',
    'Ministry of Cooperatives and MSMEs Development',
    'Ministry of Youth Affairs and Sports',
    'Ministry of East African Community and Regional Development',
    'Ministry of Gender, Culture, The Arts and Heritage',
    'Ministry of Public Service, Performance and Delivery Management',
]

SERVICE_STATUSES = [
    ('draft', 'Draft'),
    ('submitted', 'Submitted'),
    ('in_review', 'In Review'),
    ('pending_documents', 'Pending Documents'),
    ('rejected', 'Rejected'),
    ('approved', 'Approved'),
    ('completed', 'Completed'),
    ('appealed', 'Appealed'),
]

APPLICATION_STATUSES = SERVICE_STATUSES

PAYMENT_STATUSES = [
    ('pending', 'Pending'),
    ('processing', 'Processing'),
    ('completed', 'Completed'),
    ('failed', 'Failed'),
    ('refunded', 'Refunded'),
    ('cancelled', 'Cancelled'),
]

ID_TYPES = [
    ('national_id', 'National ID'),
    ('passport', 'Passport'),
    ('alien_id', 'Alien ID'),
    ('military_id', 'Military ID'),
    ('birth_certificate', 'Birth Certificate'),
    ('service_id', 'Service ID Card'),
]

GENDER_CHOICES = [
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
]

NOTIFICATION_CHANNELS = [
    ('email', 'Email'),
    ('sms', 'SMS'),
    ('push', 'Push Notification'),
    ('in_app', 'In-App'),
]

USER_ROLES = [
    ('citizen', 'Citizen'),
    ('administrator', 'Administrator'),
    ('agency_staff', 'Agency Staff'),
    ('developer', 'Developer'),
    ('auditor', 'Auditor'),
    ('support', 'Support Staff'),
]

KENYAN_BANKS = [
    ('001', 'Kenya Commercial Bank (KCB)'),
    ('002', 'Equity Bank'),
    ('003', 'Co-operative Bank of Kenya'),
    ('004', 'Absa Bank Kenya'),
    ('005', 'NCBA Bank'),
    ('006', 'Stanbic Bank Kenya'),
    ('007', 'Standard Chartered Bank Kenya'),
    ('008', 'I&M Bank'),
    ('009', 'Diamond Trust Bank (DTB)'),
    ('010', 'National Bank of Kenya (NBK)'),
    ('011', 'Consolidated Bank of Kenya'),
    ('012', 'Housing Finance Company (HFC)'),
    ('013', 'Bank of Africa Kenya'),
    ('014', 'Sidian Bank'),
    ('015', 'Ecobank Kenya'),
    ('016', 'Prime Bank'),
    ('017', 'Victoria Commercial Bank'),
    ('018', 'Guaranty Trust Bank Kenya'),
    ('019', 'Gulf African Bank'),
    ('020', 'First Community Bank'),
    ('021', 'Credit Bank'),
    ('022', 'Development Bank of Kenya'),
    ('023', 'Middle East Bank Kenya'),
    ('024', 'UBA Kenya'),
    ('025', 'Access Bank Kenya'),
    ('026', 'African Banking Corporation (ABC Bank)'),
    ('027', 'Guardian Bank'),
    ('028', 'Habib Bank AG Zurich'),
    ('029', 'Oriental Commercial Bank'),
    ('030', 'Spire Bank'),
    ('031', 'Kingdom Bank'),
    ('032', 'M Oriental Bank'),
    ('033', 'SBM Bank Kenya'),
    ('034', 'Citibank Kenya'),
    ('035', 'Jamii Bora Bank'),
    ('036', 'Rafiki Microfinance Bank'),
    ('037', 'Faulu Microfinance Bank'),
    ('038', 'Kenya Women Microfinance Bank (KWFT)'),
    ('039', 'SMEP Microfinance Bank'),
    ('040', 'Caritas Microfinance Bank'),
    ('041', 'Central Bank of Kenya (CBK)'),
]
