# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('license_class', models.CharField(choices=[('A1', 'Motorcycle (A1)'), ('A2', 'Motorcycle >250cc (A2)'), ('B', 'Light Motor Vehicle (B)'), ('C', 'Light Truck (C)'), ('D', 'PSV Matatu/Bus (D)'), ('E', 'Heavy Truck (E)'), ('F', 'Special (F)'), ('G', 'Industrial/Agricultural (G)')], max_length=3)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN/Chassis Number')),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_center', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(default='pending', max_length=30)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='transport.vehicleregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PSVLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('route', models.CharField(max_length=255)),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('sacco_name', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psv_licenses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psv_licenses', to='transport.vehicleregistration')),
            ],
            options={
                'verbose_name': 'PSV License',
                'ordering': ['-created_at'],
            },
        ),
    ]
