# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title_number', models.CharField(max_length=100)),
                ('search_purpose', models.CharField(max_length=500)),
                ('search_date', models.DateTimeField(blank=True, null=True)),
                ('search_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Search',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TitleDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title_number', models.CharField(max_length=100)),
                ('property_location', models.CharField(max_length=500)),
                ('land_size_hectares', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('tenure_type', models.CharField(default='freehold', max_length=50)),
                ('registered_owner_name', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('encumbrances', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_deeds', to='counties.county')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_deeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Title Deed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('from_owner', models.CharField(max_length=255)),
                ('to_owner', models.CharField(max_length=255)),
                ('consideration_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_type', models.CharField(default='sale', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('title_deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='land.titledeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
