# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('election_type', models.CharField(max_length=100)),
                ('political_party', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('constituency_name', models.CharField(blank=True, max_length=255)),
                ('ward_name', models.CharField(blank=True, max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=100)),
                ('is_cleared', models.BooleanField(default=False)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='counties.county')),
            ],
            options={
                'ordering': ['election_type', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('constituency_name', models.CharField(max_length=255)),
                ('ward_name', models.CharField(max_length=255)),
                ('registration_center', models.CharField(blank=True, max_length=255)),
                ('station_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('registered_voters', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='counties.county')),
            ],
            options={
                'ordering': ['county', 'constituency_name', 'ward_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('voter_number', models.CharField(max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='elections.pollingstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
