# Generated by Django 5.2.4 on 2026-05-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('exam_type', models.CharField(choices=[('kcpe', 'KCPE'), ('kcse', 'KCSE'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('degree', 'Degree'), ('professional', 'Professional')], max_length=30)),
                ('index_number', models.CharField(max_length=50)),
                ('examination_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('mean_grade', models.CharField(blank=True, max_length=10)),
                ('total_points', models.PositiveSmallIntegerField(default=0)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('loan_type', models.CharField(choices=[('undergraduate', 'Undergraduate Loan'), ('postgraduate', 'Postgraduate Loan'), ('tvet', 'TVET Loan'), ('bursary', 'Bursary')], default='undergraduate', max_length=30)),
                ('institution', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, max_length=255)),
                ('course_of_study', models.CharField(blank=True, max_length=255)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('registration_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('tvet', 'TVET Institution'), ('university', 'University'), ('tertiary', 'Tertiary College'), ('other', 'Other')], max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('proprietor_name', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('pending_documents', 'Pending Documents'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('appealed', 'Appealed')], default='draft', max_length=20)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_registrations', to='counties.county')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
